services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: '${POSTGRES_USER:?POSTGRES_USER is required}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}'
      POSTGRES_DB: '${POSTGRES_DB:?POSTGRES_DB is required}'
    ports:
      - '${POSTGRES_PORT:?POSTGRES_PORT is required}:5432'
    volumes:
      - jj_db_local_volume:/var/lib/postgresql/data

  redis:
    image: redis:latest

    ports:
      - '${REDIS_PORT:?REDIS_PORT is required}:6379'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-password}
    volumes:
      - jj_redis_local_volume:/data

    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD:-password}', '--appendonly', 'yes'] # enables persistence

  minio:
    image: quay.io/minio/minio:latest

    ports:
      - '${MINIO_PORT:?MINIO_PORT is required}:9000'
      - '${MINIO_UI_PORT:?MINIO_UI_PORT is required}:9001' # Web UI

    env_file:
      - ${PROJECT_ROOT}/config/.env.dev
      - ${PROJECT_ROOT}/.env.local
      - ${PROJECT_ROOT}/.env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    volumes:
      - jj_minio_local_volume:/data

    command: server /data --console-address ":9001"

  minio-init:
    image: minio/mc
    depends_on:
      minio:
        condition: service_started

    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_BUCKET: ${MINIO_BUCKET}

    volumes:
      - ${PROJECT_ROOT}/scripts/init_minio.sh:/init_minio.sh:ro
      - ${PROJECT_ROOT}/seed/minio:/seed:ro

    entrypoint: ['/bin/sh', '/init_minio.sh']

volumes:
  jj_db_local_volume:
  jj_redis_local_volume:
  jj_minio_local_volume:
